config/urls.py
from allauth.account import views as allauth
from django.conf import settings
from django.conf.urls import include
from django.urls import path
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from hijos.users.views import LodgesList

urlpatterns = [
    path(
        '',
        view=LodgesList.as_view(),
        name='home'
    ),

    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),

    # User management
    path('users/', include('hijos.users.urls', namespace='users')),
    path('accounts/login/', allauth.login, name='account_login'),
    path('accounts/logout/', allauth.logout, name='account_logout'),
    # redirect signup to login
    path('accounts/signup/', allauth.login, name='account_signup'),
    path(
        'accounts/password/change/',
        allauth.password_change,
        name='account_change_password'
    ),
    path(
        'accounts/password/set/',
        allauth.password_set,
        name='account_set_password'
    ),
    path(
        'accounts/inactive/',
        allauth.account_inactive,
        name='account_inactive'
    ),
    path('email/', allauth.email, name='account_email'),

    path('treasure/', include('hijos.treasure.urls', namespace='treasure')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path('400/', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        path('403/', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        path('404/', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        path('500/', default_views.server_error),
    ]

hijos/treasure/urls.py
from django.urls import path

from hijos.treasure import forms, views

app_name = 'treasure'
urlpatterns = [
    path(
        'lodges/<int:pk>/lodgeaccounts/',
        view=views.LodgeAccountsByLodgeList.as_view(),
        name='lodgeaccount-list'
    ),
    path(
        'lodgeaccounts/add/',
        view=views.LodgeAccountCreateView.as_view(),
        name='lodgeaccount-create'
    ),
    path(
        'lodgeaccounts/<int:pk>/',
        view=views.LodgeAccountDetailView.as_view(),
        name='lodgeaccount-detail'
    ),
    path(
        'lodges/<int:pk>/periods/',
        view=views.PeriodsByLodgeList.as_view(),
        name='period-list'
    ),
    path(
        'periods/add/',
        view=views.PeriodCreateView.as_view(),
        name='period-create'
    ),
    path(
        'periods/<int:pk>/',
        view=views.PeriodDetailView.as_view(),
        name='period-detail'
    ),
    path(
        'lodges/<int:pk>/invoices/',
        view=views.InvoicesByLodgeList.as_view(),
        name='invoice-list'
    ),
    path(
        'invoices/add/',
        view=views.InvoiceCreateView.as_view(),
        name='invoice-create'
    ),
    path(
        'invoices/<int:pk>/',
        view=views.InvoiceDetailView.as_view(),
        name='invoice-detail'
    ),
    path(
        'lodges/<int:pk>/deposits/',
        view=views.DepositsByLodgeList.as_view(),
        name='deposit-list'
    ),
    path(
        'deposits/add/',
        view=views.DepositCreateView.as_view(),
        name='deposit-create'
    ),
    path(
        'deposits/<int:pk>/',
        view=views.DepositDetailView.as_view(),
        name='deposit-detail'
    ),
    path(
        'lodges/<int:pk>/charges/',
        view=views.ChargesByLodgeList.as_view(),
        name='charge-list'
    ),
    path(
        'charges/add/',
        view=views.ChargeCreateView.as_view(),
        name='charge-create'
    ),
    path(
        'charges/<int:pk>/',
        view=views.ChargeDetailView.as_view(),
        name='charge-detail'
    ),
    path(
        'lodges/<int:pk>/grandlodgedeposits/',
        view=views.GrandLodgeDepositsByLodgeList.as_view(),
        name='grandlodgedeposit-list'
    ),
    path(
        'grandlodgedeposits/add/',
        view=views.GrandLodgeDepositCreateView.as_view(),
        name='grandlodgedeposit-create'
    ),
    path(
        'grandlodgedeposits/<int:pk>/edit/',
        view=views.GrandLodgeDepositUpdateView.as_view(),
        name='grandlodgedeposit-update'
    ),
    path(
        'grandlodgedeposits/<int:pk>/accredit/',
        view=forms.GrandLodgeDepositAccredit.as_view(),
        name='grandlodgedeposit-accredit'
    ),
    path(
        'grandlodgedeposits/<int:pk>/reject/',
        view=forms.GrandLodgeDepositReject.as_view(),
        name='grandlodgedeposit-reject'
    ),
    path(
        'grandlodgedeposits/<int:pk>/',
        view=views.GrandLodgeDepositDetailView.as_view(),
        name='grandlodgedeposit-detail'
    ),
    path(
        'lodges/<int:pk>/ingresses/',
        view=views.LodgeAccountIngressesByLodgeList.as_view(),
        name='lodgeaccountingress-list'
    ),
    path(
        'ingresses/add/',
        view=views.LodgeAccountIngressCreateView.as_view(),
        name='lodgeaccountingress-create'
    ),
    path(
        'ingresses/<int:pk>/',
        view=views.LodgeAccountIngressDetailView.as_view(),
        name='lodgeaccountingress-detail'
    ),
    path(
        'lodges/<int:pk>/egresses/',
        view=views.LodgeAccountEgressesByLodgeList.as_view(),
        name='lodgeaccountegress-list'
    ),
    path(
        'egresses/add/',
        view=views.LodgeAccountEgressCreateView.as_view(),
        name='lodgeaccountegress-create'
    ),
    path(
        'egresses/<int:pk>/',
        view=views.LodgeAccountEgressDetailView.as_view(),
        name='lodgeaccountegress-detail'
    ),
    path(
        'lodges/<int:pk>/transfers/',
        view=views.LodgeAccountTransfersByLodgeList.as_view(),
        name='lodgeaccounttransfer-list'
    ),
    path(
        'transfers/add/',
        view=views.LodgeAccountTransferCreateView.as_view(),
        name='lodgeaccounttransfer-create'
    ),
    path(
        'transfers/<int:pk>/',
        view=views.LodgeAccountTransferDetailView.as_view(),
        name='lodgeaccounttransfer-detail'
    ),
    path(
        'lodges/<int:pk>/debtors/',
        view=views.DebtorsByLodgeList.as_view(),
        name='debtor-list'
    )
]

hijos/users/urls.py
from django.urls import path

from hijos.users import views

app_name = 'users'
urlpatterns = [
    path(
        'users/',
        view=views.UserListView.as_view(),
        name='user-list'
    ),
    path(
        'users/add/',
        view=views.UserCreateView.as_view(),
        name='user-create'
    ),
    path(
        'users/<username>/',
        view=views.UserDetailView.as_view(),
        name='user-detail'
    ),
    path(
        'lodges/',
        view=views.LodgesList.as_view(),
        name='lodge-list'
    ),
    path(
        'lodges/<int:pk>/',
        view=views.LodgeDetailView.as_view(),
        name='lodge-detail'
    ),
    path(
        'lodges/<int:pk>/affiliations/',
        view=views.AffiliationsByLodgeList.as_view(),
        name='affiliation-list'
    ),
    path(
        'affiliations/<int:pk>/',
        view=views.AffiliationDetailView.as_view(),
        name='affiliation-detail'
    ),
    path(
        'affiliations/add/',
        view=views.AffiliationCreateView.as_view(),
        name='affiliation-create'
    )
]

hijos/treasure/views.py
from decimal import Decimal

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Avg, Max, Min, Q, Sum
from django.shortcuts import get_object_or_404
from django.views.generic import CreateView, DetailView, ListView, UpdateView

from hijos.treasure import models
from hijos.users import models as users


class LodgeAccountsByLodgeList(LoginRequiredMixin, ListView):
    template_name = 'treasure/lodgeaccount_list.html'
    context_object_name = 'lodge_accounts'

    def get_queryset(self):
        self.lodge = get_object_or_404(
            users.Lodge, pk=self.kwargs['pk']
        )
        return models.LodgeAccount.objects.filter(
            handler__lodge=self.lodge
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['lodge'] = self.lodge
        return context


class LodgeAccountDetailView(LoginRequiredMixin, DetailView):
    model = models.LodgeAccount
    context_object_name = 'lodge_account'
    template_name = 'treasure/lodgeaccount_detail.html'


class LodgeAccountCreateView(LoginRequiredMixin, CreateView):
    model = models.LodgeAccount
    fields = ['handler', 'description']
    template_name = 'treasure/lodgeaccount_add.html'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.last_modified_by = self.request.user
        return super().form_valid(form)


class PeriodsByLodgeList(LoginRequiredMixin, ListView):
    template_name = 'treasure/period_list.html'
    context_object_name = 'periods'

    def get_queryset(self):
        self.lodge = get_object_or_404(
            users.Lodge, pk=self.kwargs['pk']
        )
        return models.Period.objects.filter(
            lodge=self.lodge
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['lodge'] = self.lodge
        return context


class PeriodDetailView(LoginRequiredMixin, DetailView):
    model = models.Period
    context_object_name = 'period'
    template_name = 'treasure/period_detail.html'


class PeriodCreateView(LoginRequiredMixin, CreateView):
    model = models.Period
    fields = ['lodge', 'begin', 'end', 'price_multiplier', 'send_email']
    template_name = 'treasure/period_add.html'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.last_modified_by = self.request.user
        return super().form_valid(form)


class InvoicesByLodgeList(LoginRequiredMixin, ListView):
    template_name = 'treasure/invoice_list.html'
    context_object_name = 'invoices'

    def get_queryset(self):
        self.lodge = get_object_or_404(
            users.Lodge, pk=self.kwargs['pk']
        )
        return models.Invoice.objects.filter(
            period__lodge=self.lodge
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['lodge'] = self.lodge
        return context


class InvoiceDetailView(LoginRequiredMixin, DetailView):
    model = models.Invoice
    context_object_name = 'invoice'
    template_name = 'treasure/invoice_detail.html'


class InvoiceCreateView(LoginRequiredMixin, CreateView):
    model = models.Invoice
    fields = ['period', 'affiliation', 'amount', 'send_email']
    template_name = 'treasure/invoice_add.html'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.last_modified_by = self.request.user
        return super().form_valid(form)


class DepositsByLodgeList(LoginRequiredMixin, ListView):
    template_name = 'treasure/deposit_list.html'
    context_object_name = 'deposits'

    def get_queryset(self):
        self.lodge = get_object_or_404(
            users.Lodge, pk=self.kwargs['pk']
        )
        return models.Deposit.objects.filter(
            payer__lodge=self.lodge
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['lodge'] = self.lodge
        return context


class DepositDetailView(LoginRequiredMixin, DetailView):
    model = models.Deposit
    context_object_name = 'deposit'
    template_name = 'treasure/deposit_detail.html'


class DepositCreateView(LoginRequiredMixin, CreateView):
    model = models.Deposit
    fields = [
        'payer',
        'lodge_account',
        'amount',
        'description',
        'send_email',
        'receipt'
    ]
    template_name = 'treasure/deposit_add.html'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.last_modified_by = self.request.user
        return super().form_valid(form)


class ChargesByLodgeList(LoginRequiredMixin, ListView):
    template_name = 'treasure/charge_list.html'
    context_object_name = 'charges'

    def get_queryset(self):
        self.lodge = get_object_or_404(
            users.Lodge, pk=self.kwargs['pk']
        )
        return models.Charge.objects.filter(
            debtor__lodge=self.lodge
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['lodge'] = self.lodge
        return context


class ChargeDetailView(LoginRequiredMixin, DetailView):
    model = models.Charge
    context_object_name = 'charge'
    template_name = 'treasure/charge_detail.html'


class ChargeCreateView(LoginRequiredMixin, CreateView):
    model = models.Charge
    fields = [
        'debtor',
        'charge_type',
        'amount',
        'description',
        'send_email'
    ]
    template_name = 'treasure/charge_add.html'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.last_modified_by = self.request.user
        return super().form_valid(form)


class GrandLodgeDepositsByLodgeList(LoginRequiredMixin, ListView):
    template_name = 'treasure/grandlodgedeposit_list.html'
    context_object_name = 'grand_lodge_deposits'

    def get_queryset(self):
        self.lodge = get_object_or_404(
            users.Lodge, pk=self.kwargs['pk']
        )
        return models.GrandLodgeDeposit.objects.filter(
            payer__lodge=self.lodge
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['lodge'] = self.lodge
        return context


class GrandLodgeDepositDetailView(LoginRequiredMixin, DetailView):
    model = models.GrandLodgeDeposit
    context_object_name = 'grand_lodge_deposit'
    template_name = 'treasure/grandlodgedeposit_detail.html'


class GrandLodgeDepositCreateView(LoginRequiredMixin, CreateView):
    model = models.GrandLodgeDeposit
    fields = [
        'payer',
        'amount',
        'description',
        'receipt',
        'send_email'
    ]
    template_name = 'treasure/grandlodgedeposit_add.html'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.last_modified_by = self.request.user
        return super().form_valid(form)


class GrandLodgeDepositUpdateView(LoginRequiredMixin, UpdateView):
    model = models.GrandLodgeDeposit
    fields = ['receipt']
    template_name = 'treasure/grandlodgedeposit_edit.html'

    def form_valid(self, form):
        form.instance.last_modified_by = self.request.user
        return super().form_valid(form)


class LodgeAccountIngressesByLodgeList(LoginRequiredMixin, ListView):
    template_name = 'treasure/lodgeaccountingresses_list.html'
    context_object_name = 'ingresses'

    def get_queryset(self):
        self.lodge = get_object_or_404(
            users.Lodge, pk=self.kwargs['pk']
        )
        return models.LodgeAccountIngress.objects.filter(
            lodge_account__handler__lodge=self.lodge
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['lodge'] = self.lodge
        return context


class LodgeAccountIngressDetailView(LoginRequiredMixin, DetailView):
    model = models.LodgeAccountIngress
    context_object_name = 'ingress'
    template_name = 'treasure/lodgeaccountingress_detail.html'


class LodgeAccountIngressCreateView(LoginRequiredMixin, CreateView):
    model = models.LodgeAccountIngress
    fields = [
        'lodge_account',
        'ingress_type',
        'amount',
        'description',
        'receipt'
    ]
    template_name = 'treasure/lodgeaccountingress_add.html'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.last_modified_by = self.request.user
        return super().form_valid(form)


class LodgeAccountEgressesByLodgeList(LoginRequiredMixin, ListView):
    template_name = 'treasure/lodgeaccountegresses_list.html'
    context_object_name = 'egresses'

    def get_queryset(self):
        self.lodge = get_object_or_404(
            users.Lodge, pk=self.kwargs['pk']
        )
        return models.LodgeAccountEgress.objects.filter(
            lodge_account__handler__lodge=self.lodge
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['lodge'] = self.lodge
        return context


class LodgeAccountEgressDetailView(LoginRequiredMixin, DetailView):
    model = models.LodgeAccountEgress
    context_object_name = 'egress'
    template_name = 'treasure/lodgeaccountegress_detail.html'


class LodgeAccountEgressCreateView(LoginRequiredMixin, CreateView):
    model = models.LodgeAccountEgress
    fields = [
        'lodge_account',
        'egress_type',
        'amount',
        'description',
        'receipt'
    ]
    template_name = 'treasure/lodgeaccountegress_add.html'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.last_modified_by = self.request.user
        return super().form_valid(form)

hijos/templates/treasure/charge_add.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}{% trans "add charge" %}{% endblock %}

{% block content %}
  <h1>{% trans "Charge" %} {{ charge.id }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'treasure:charge-create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">{% trans "Add" %}</button>
      </div>
    </div>
  </form>
{% endblock %}

hijos/templates/treasure/charge_detail.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}{% trans "charge detail" %}{% endblock %}

{% block content %}
<div class="row">
  <div class="col"><h1>{% trans "Charge" %} #{{ charge.id }}</h1></div>
</div>
<div class="row">
  <div class="col">
    {% trans "Debtor" %}: 
    <a href="{% url 'users:user-detail' charge.debtor.user.username %}">
      <b>{{ charge.debtor }}</b>
    </a>
  </div>
</div>
<div class="row">
  <div class="col">
    {% trans "Charge Type" %}: 
    {% if charge.charge_type == "I" %}
      {% trans "Initiation" %}
    {% elif charge.charge_type == "P" %}
      {% trans "Passed" %}
    {% elif charge.charge_type == "R" %}
      {% trans "Raised" %}
    {% elif charge.charge_type == "O" %}
      {% trans "Other" %}
    {% else %}
      {% trans "Unknown" %}
    {% endif %}
  </div>
</div>
<div class="row">
  <div class="col">{% trans "Amount" %}: $ {{ charge.amount }}</div>
</div>
<div class="row">
  <div class="col">{% trans "Description" %}: {{ charge.description }}</div>
</div>
<div class="row">
  <div class="col">
  {% blocktrans with created_by=charge.created_by created_on=charge.created_on %}
  Created by {{ created_by }} on {{ created_on }}.
  {% endblocktrans %}
  </div>
</div>
{% if charge.created_on != charge.last_modified_on %}
<div class="row">
  <div class="col">
  {% blocktrans with last_modified_by=charge.last_modified_by last_modified_on=dcharge.last_modified_on %}
  Last modified by {{ last_modified_by }} on {{ last_modified_on }}.
  {% endblocktrans %}
  </div>
</div>
{% endif %}
{% endblock %}

hijos/templates/treasure/debtors_list.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}{% trans "debtors list" %}{% endblock %}

{% block content %}
<div class="row">
  <div class="col"><h1>{% trans "Debtors" %} - {{ lodge }}</h1></div>
</div>
<div class="row">
  <div class="col">
    <p>{% trans "Total" %} $ {{ aggregations.debt_sum }}</p>
    <p>{% trans "Maximum" %} $ {{ aggregations.debt_min }}</p>
    <p>{% trans "Average" %} $ {{ aggregations.debt_avg }}</p>
    <p>{% trans "Minimum" %} $ {{ aggregations.debt_max }}</p>
  </div>
</div>
<div class="row">
  <div class="col">
    <ul>
      {% for d in debtor_accounts %}
      <div class="row">
        <div class="col">
          <a href="{% url 'users:affiliation-detail' d.affiliation.id %}">
            <b>{{ d.affiliation }}</b>
          </a>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <b>{% trans "Balance" %} $ {{ d.balance }}</b>
        </div>
      </div>
      {% endfor %}
    </ul>
  </div>
</div>
<div class="row">
  <div class="col">
    {% trans "Total entries" %} {{ debtor_accounts.count }}
  </div>
</div>
{% endblock %}

hijos/templates/treasure/deposit_detail.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}{% trans "deposit detail" %}{% endblock %}

{% block content %}
<div class="row">
  <div class="col"><h1>{% trans "Deposit" %} #{{ deposit.id }}</h1></div>
</div>
<div class="row">
  <div class="col">
    {% trans "Payer" %}: 
    <a href="{% url 'users:user-detail' deposit.payer.user.username %}">
      <b>{{ deposit.payer }}</b>
    </a>
  </div>
</div>
<div class="row">
  <div class="col">
    {% trans "Lodge Account" %}: 
    <a href="{% url 'treasure:lodgeaccount-detail' deposit.lodge_account.id %}">
      {{ deposit.lodge_account.handler }}
    </a>
  </div>
</div>
<div class="row">
  <div class="col">{% trans "Amount" %}: $ {{ deposit.amount }}</div>
</div>
<div class="row">
  <div class="col">{% trans "Description" %}: {{ deposit.description }}</div>
</div>
{% if deposit.receipt %}
<div class="row">
  <div class="col">
    <img src="{{ deposit.receipt.url }}">
  </div>
</div>
{% endif %}
<div class="row">
  <div class="col">
  {% blocktrans with created_by=deposit.created_by created_on=deposit.created_on %}
  Created by {{ created_by }} on {{ created_on }}.
  {% endblocktrans %}
  </div>
</div>
{% if deposit.created_on != deposit.last_modified_on %}
<div class="row">
  <div class="col">
  {% blocktrans with last_modified_by=deposit.last_modified_by last_modified_on=deposit.last_modified_on %}
  Last modified by {{ last_modified_by }} on {{ last_modified_on }}.
  {% endblocktrans %}
  </div>
</div>
{% endif %}
{% endblock %}

hijos/templates/treasure/deposit_list.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}{% trans "deposit list" %}{% endblock %}

{% block content %}
<div class="row">
  <div class="col"><h1>{% trans "Deposits" %} - {{ lodge }}</h1></div>
</div>
<div class="row">
  <div class="col">
    <ul>
      {% for deposit in deposits %}
      <div class="row">
        <div class="col">
          <a href="{% url 'treasure:deposit-detail' deposit.id %}">
            <b>{{ deposit }}</b>
          </a>
        </div>
      </div>
      {% endfor %}
    </ul>
  </div>
</div>
{% endblock %}

hijos/templates/treasure/grandlodgedeposit_edit.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}{% trans "update grand lodge deposit" %}{% endblock %}

{% block content %}
  <h1>{% trans "Grand Lodge Deposit" %} {{ grandlodgedeposit.id }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'treasure:grandlodgedeposit-update' grandlodgedeposit.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">{% trans "Update" %}</button>
      </div>
    </div>
  </form>
{% endblock %}

hijos/templates/treasure/grandlodgedeposit_list.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}{% trans "grand lodge deposit list" %}{% endblock %}

{% block content %}
<div class="row">
  <div class="col"><h1>{% trans "Grand Lodge Deposits" %} - {{ lodge }}</h1></div>
</div>
<div class="row">
  <div class="col">
    <ul>
      {% for grand_lodge_deposit in grand_lodge_deposits %}
      <div class="row">
        <div class="col">
          <a href="{% url 'treasure:grandlodgedeposit-detail' grand_lodge_deposit.id %}">
            <b>{{ grand_lodge_deposit }}</b>
          </a>
        </div>
      </div>
      {% endfor %}
    </ul>
  </div>
</div>
{% endblock %}

hijos/templates/treasure/lodgeaccountingress_add.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}{% trans "add lodge account ingress" %}{% endblock %}

{% block content %}
  <h1>{% trans "Lodge Account Ingress" %} {{ lodgeaccountingress.id }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'treasure:lodgeaccountingress-create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">{% trans "Add" %}</button>
      </div>
    </div>
  </form>
{% endblock %}

hijos/templates/treasure/lodgeaccountingress_detail.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}{% trans "lodge account ingress detail" %}{% endblock %}

{% block content %}
<div class="row">
  <div class="col"><h1>{% trans "Lodge Account Ingress" %} #{{ ingress.id }}</h1></div>
</div>
<div class="row">
  <div class="col">
    {% trans "Lodge Account" %}: 
    <a href="{% url 'treasure:lodgeaccount-detail' ingress.lodge_account.id %}">
      <b>{{ ingress.lodge_account }}</b>
    </a>
  </div>
</div>
<div class="row">
  <div class="col">
    {% trans "Ingress Type" %}: 
    {% if ingress.ingress_type == "D" %}
      {% trans "Donation" %}
    {% elif ingress.ingress_type == "PH" %}
      {% trans "Philantropy" %}
    {% elif ingress.ingress_type == "PA" %}
      {% trans "Payment" %}
    {% elif ingress.ingress_type == "O" %}
      {% trans "Other" %}
    {% else %}
      {% trans "Unknown" %}
    {% endif %}
  </div>
</div>
<div class="row">
  <div class="col">{% trans "Amount" %}: $ {{ ingress.amount }}</div>
</div>
<div class="row">
  <div class="col">{% trans "Description" %}: {{ ingress.description }}</div>
</div>
<div class="row">
  <div class="col">
  {% blocktrans with created_by=ingress.created_by created_on=ingress.created_on %}
  Created by {{ created_by }} on {{ created_on }}.
  {% endblocktrans %}
  </div>
</div>
{% if ingress.created_on != ingress.last_modified_on %}
<div class="row">
  <div class="col">
  {% blocktrans with last_modified_by=ingress.last_modified_by last_modified_on=ingress.last_modified_on %}
  Last modified by {{ last_modified_by }} on {{ last_modified_on }}.
  {% endblocktrans %}
  </div>
</div>
{% endif %}
{% endblock %}

hijos/templates/treasure/lodgeaccountingress_list.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}{% trans "lodge account ingress list" %}{% endblock %}

{% block content %}
<div class="row">
  <div class="col"><h1>{% trans "Lodge Account Ingresses" %} - {{ lodge }}</h1></div>
</div>
<div class="row">
  <div class="col">
    <ul>
      {% for ingress in ingresses %}
      <div class="row">
        <div class="col">
          <a href="{% url 'treasure:lodgeaccountingress-detail' ingress.id %}">
            <b>{{ ingress }}</b>
          </a>
        </div>
      </div>
      {% endfor %}
    </ul>
  </div>
</div>
{% endblock %}