config/urls.py
from allauth.account import views as allauth
from django.conf import settings
from django.conf.urls import include
from django.urls import path
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from hijos.users.views import LodgesList

urlpatterns = [
    path(
        '',
        view=LodgesList.as_view(),
        name='home'
    ),

    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),

    # User management
    path('users/', include('hijos.users.urls', namespace='users')),
    path('accounts/login/', allauth.login, name='account_login'),
    path('accounts/logout/', allauth.logout, name='account_logout'),
    # redirect signup to login
    path('accounts/signup/', allauth.login, name='account_signup'),
    path(
        'accounts/password/change/',
        allauth.password_change,
        name='account_change_password'
    ),
    path(
        'accounts/password/set/',
        allauth.password_set,
        name='account_set_password'
    ),
    path(
        'accounts/inactive/',
        allauth.account_inactive,
        name='account_inactive'
    ),
    path('email/', allauth.email, name='account_email'),

    path('treasure/', include('hijos.treasure.urls', namespace='treasure')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path('400/', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        path('403/', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        path('404/', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        path('500/', default_views.server_error),
    ]

hijos/treasure/urls.py
from django.urls import path

from hijos.treasure import forms, views

app_name = 'treasure'
urlpatterns = [
    path(
        'lodges/<int:pk>/lodgeaccounts/',
        view=views.LodgeAccountsByLodgeList.as_view(),
        name='lodgeaccount-list'
    ),
    path(
        'lodgeaccounts/add/',
        view=views.LodgeAccountCreateView.as_view(),
        name='lodgeaccount-create'
    ),
    path(
        'lodgeaccounts/<int:pk>/',
        view=views.LodgeAccountDetailView.as_view(),
        name='lodgeaccount-detail'
    ),
    path(
        'lodges/<int:pk>/periods/',
        view=views.PeriodsByLodgeList.as_view(),
        name='period-list'
    ),
    path(
        'periods/add/',
        view=views.PeriodCreateView.as_view(),
        name='period-create'
    ),
    path(
        'periods/<int:pk>/',
        view=views.PeriodDetailView.as_view(),
        name='period-detail'
    ),
    path(
        'lodges/<int:pk>/invoices/',
        view=views.InvoicesByLodgeList.as_view(),
        name='invoice-list'
    ),
    path(
        'invoices/add/',
        view=views.InvoiceCreateView.as_view(),
        name='invoice-create'
    ),
    path(
        'invoices/<int:pk>/',
        view=views.InvoiceDetailView.as_view(),
        name='invoice-detail'
    ),
    path(
        'lodges/<int:pk>/deposits/',
        view=views.DepositsByLodgeList.as_view(),
        name='deposit-list'
    ),
    path(
        'deposits/add/',
        view=views.DepositCreateView.as_view(),
        name='deposit-create'
    ),
    path(
        'deposits/<int:pk>/',
        view=views.DepositDetailView.as_view(),
        name='deposit-detail'
    ),
    path(
        'lodges/<int:pk>/charges/',
        view=views.ChargesByLodgeList.as_view(),
        name='charge-list'
    ),
    path(
        'charges/add/',
        view=views.ChargeCreateView.as_view(),
        name='charge-create'
    ),
    path(
        'charges/<int:pk>/',
        view=views.ChargeDetailView.as_view(),
        name='charge-detail'
    ),
    path(
        'lodges/<int:pk>/grandlodgedeposits/',
        view=views.GrandLodgeDepositsByLodgeList.as_view(),
        name='grandlodgedeposit-list'
    ),
    path(
        'grandlodgedeposits/add/',
        view=views.GrandLodgeDepositCreateView.as_view(),
        name='grandlodgedeposit-create'
    ),
    path(
        'grandlodgedeposits/<int:pk>/edit/',
        view=views.GrandLodgeDepositUpdateView.as_view(),
        name='grandlodgedeposit-update'
    ),
    path(
        'grandlodgedeposits/<int:pk>/accredit/',
        view=forms.GrandLodgeDepositAccredit.as_view(),
        name='grandlodgedeposit-accredit'
    ),
    path(
        'grandlodgedeposits/<int:pk>/reject/',
        view=forms.GrandLodgeDepositReject.as_view(),
        name='grandlodgedeposit-reject'
    ),
    path(
        'grandlodgedeposits/<int:pk>/',
        view=views.GrandLodgeDepositDetailView.as_view(),
        name='grandlodgedeposit-detail'
    ),
    path(
        'lodges/<int:pk>/ingresses/',
        view=views.LodgeAccountIngressesByLodgeList.as_view(),
        name='lodgeaccountingress-list'
    ),
    path(
        'ingresses/add/',
        view=views.LodgeAccountIngressCreateView.as_view(),
        name='lodgeaccountingress-create'
    ),
    path(
        'ingresses/<int:pk>/',
        view=views.LodgeAccountIngressDetailView.as_view(),
        name='lodgeaccountingress-detail'
    ),
    path(
        'lodges/<int:pk>/egresses/',
        view=views.LodgeAccountEgressesByLodgeList.as_view(),
        name='lodgeaccountegress-list'
    ),
    path(
        'egresses/add/',
        view=views.LodgeAccountEgressCreateView.as_view(),
        name='lodgeaccountegress-create'
    ),
    path(
        'egresses/<int:pk>/',
        view=views.LodgeAccountEgressDetailView.as_view(),
        name='lodgeaccountegress-detail'
    ),
    path(
        'lodges/<int:pk>/transfers/',
        view=views.LodgeAccountTransfersByLodgeList.as_view(),
        name='lodgeaccounttransfer-list'
    ),
    path(
        'transfers/add/',
        view=views.LodgeAccountTransferCreateView.as_view(),
        name='lodgeaccounttransfer-create'
    ),
    path(
        'transfers/<int:pk>/',
        view=views.LodgeAccountTransferDetailView.as_view(),
        name='lodgeaccounttransfer-detail'
    ),
    path(
        'lodges/<int:pk>/debtors/',
        view=views.DebtorsByLodgeList.as_view(),
        name='debtor-list'
    )
]

hijos/users/urls.py
from django.urls import path

from hijos.users import views

app_name = 'users'
urlpatterns = [
    path(
        'users/',
        view=views.UserListView.as_view(),
        name='user-list'
    ),
    path(
        'users/add/',
        view=views.UserCreateView.as_view(),
        name='user-create'
    ),
    path(
        'users/<username>/',
        view=views.UserDetailView.as_view(),
        name='user-detail'
    ),
    path(
        'lodges/',
        view=views.LodgesList.as_view(),
        name='lodge-list'
    ),
    path(
        'lodges/<int:pk>/',
        view=views.LodgeDetailView.as_view(),
        name='lodge-detail'
    ),
    path(
        'lodges/<int:pk>/affiliations/',
        view=views.AffiliationsByLodgeList.as_view(),
        name='affiliation-list'
    ),
    path(
        'affiliations/<int:pk>/',
        view=views.AffiliationDetailView.as_view(),
        name='affiliation-detail'
    ),
    path(
        'affiliations/add/',
        view=views.AffiliationCreateView.as_view(),
        name='affiliation-create'
    )
]

hijos/treasure/views.py
from decimal import Decimal

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Avg, Max, Min, Q, Sum
from django.shortcuts import get_object_or_404
from django.views.generic import CreateView, DetailView, ListView, UpdateView

from hijos.treasure import models
from hijos.users import models as users


class LodgeAccountsByLodgeList(LoginRequiredMixin, ListView):
    template_name = 'treasure/lodgeaccount_list.html'
    context_object_name = 'lodge_accounts'

    def get_queryset(self):
        self.lodge = get_object_or_404(
            users.Lodge, pk=self.kwargs['pk']
        )
        return models.LodgeAccount.objects.filter(
            handler__lodge=self.lodge
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['lodge'] = self.lodge
        return context


class LodgeAccountDetailView(LoginRequiredMixin, DetailView):
    model = models.LodgeAccount
    context_object_name = 'lodge_account'
    template_name = 'treasure/lodgeaccount_detail.html'


class LodgeAccountCreateView(LoginRequiredMixin, CreateView):
    model = models.LodgeAccount
    fields = ['handler', 'description']
    template_name = 'treasure/lodgeaccount_add.html'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.last_modified_by = self.request.user
        return super().form_valid(form)


class PeriodsByLodgeList(LoginRequiredMixin, ListView):
    template_name = 'treasure/period_list.html'
    context_object_name = 'periods'

    def get_queryset(self):
        self.lodge = get_object_or_404(
            users.Lodge, pk=self.kwargs['pk']
        )
        return models.Period.objects.filter(
            lodge=self.lodge
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['lodge'] = self.lodge
        return context


class PeriodDetailView(LoginRequiredMixin, DetailView):
    model = models.Period
    context_object_name = 'period'
    template_name = 'treasure/period_detail.html'


class PeriodCreateView(LoginRequiredMixin, CreateView):
    model = models.Period
    fields = ['lodge', 'begin', 'end', 'price_multiplier', 'send_email']
    template_name = 'treasure/period_add.html'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.last_modified_by = self.request.user
        return super().form_valid(form)


class InvoicesByLodgeList(LoginRequiredMixin, ListView):
    template_name = 'treasure/invoice_list.html'
    context_object_name = 'invoices'

    def get_queryset(self):
        self.lodge = get_object_or_404(
            users.Lodge, pk=self.kwargs['pk']
        )
        return models.Invoice.objects.filter(
            period__lodge=self.lodge
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['lodge'] = self.lodge
        return context


class InvoiceDetailView(LoginRequiredMixin, DetailView):
    model = models.Invoice
    context_object_name = 'invoice'
    template_name = 'treasure/invoice_detail.html'


class InvoiceCreateView(LoginRequiredMixin, CreateView):
    model = models.Invoice
    fields = ['period', 'affiliation', 'amount', 'send_email']
    template_name = 'treasure/invoice_add.html'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.last_modified_by = self.request.user
        return super().form_valid(form)


class DepositsByLodgeList(LoginRequiredMixin, ListView):
    template_name = 'treasure/deposit_list.html'
    context_object_name = 'deposits'

    def get_queryset(self):
        self.lodge = get_object_or_404(
            users.Lodge, pk=self.kwargs['pk']
        )
        return models.Deposit.objects.filter(
            payer__lodge=self.lodge
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['lodge'] = self.lodge
        return context


class DepositDetailView(LoginRequiredMixin, DetailView):
    model = models.Deposit
    context_object_name = 'deposit'
    template_name = 'treasure/deposit_detail.html'


class DepositCreateView(LoginRequiredMixin, CreateView):
    model = models.Deposit
    fields = [
        'payer',
        'lodge_account',
        'amount',
        'description',
        'send_email',
        'receipt'
    ]
    template_name = 'treasure/deposit_add.html'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.last_modified_by = self.request.user
        return super().form_valid(form)


class ChargesByLodgeList(LoginRequiredMixin, ListView):
    template_name = 'treasure/charge_list.html'
    context_object_name = 'charges'

    def get_queryset(self):
        self.lodge = get_object_or_404(
            users.Lodge, pk=self.kwargs['pk']
        )
        return models.Charge.objects.filter(
            debtor__lodge=self.lodge
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['lodge'] = self.lodge
        return context


class ChargeDetailView(LoginRequiredMixin, DetailView):
    model = models.Charge
    context_object_name = 'charge'
    template_name = 'treasure/charge_detail.html'


class ChargeCreateView(LoginRequiredMixin, CreateView):
    model = models.Charge
    fields = [
        'debtor',
        'charge_type',
        'amount',
        'description',
        'send_email'
    ]
    template_name = 'treasure/charge_add.html'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.last_modified_by = self.request.user
        return super().form_valid(form)


class GrandLodgeDepositsByLodgeList(LoginRequiredMixin, ListView):
    template_name = 'treasure/grandlodgedeposit_list.html'
    context_object_name = 'grand_lodge_deposits'

    def get_queryset(self):
        self.lodge = get_object_or_404(
            users.Lodge, pk=self.kwargs['pk']
        )
        return models.GrandLodgeDeposit.objects.filter(
            payer__lodge=self.lodge
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['lodge'] = self.lodge
        return context


class GrandLodgeDepositDetailView(LoginRequiredMixin, DetailView):
    model = models.GrandLodgeDeposit
    context_object_name = 'grand_lodge_deposit'
    template_name = 'treasure/grandlodgedeposit_detail.html'


class GrandLodgeDepositCreateView(LoginRequiredMixin, CreateView):
    model = models.GrandLodgeDeposit
    fields = [
        'payer',
        'amount',
        'description',
        'receipt',
        'send_email'
    ]
    template_name = 'treasure/grandlodgedeposit_add.html'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.last_modified_by = self.request.user
        return super().form_valid(form)


class GrandLodgeDepositUpdateView(LoginRequiredMixin, UpdateView):
    model = models.GrandLodgeDeposit
    fields = ['receipt']
    template_name = 'treasure/grandlodgedeposit_edit.html'

    def form_valid(self, form):
        form.instance.last_modified_by = self.request.user
        return super().form_valid(form)


class LodgeAccountIngressesByLodgeList(LoginRequiredMixin, ListView):
    template_name = 'treasure/lodgeaccountingresses_list.html'
    context_object_name = 'ingresses'

    def get_queryset(self):
        self.lodge = get_object_or_404(
            users.Lodge, pk=self.kwargs['pk']
        )
        return models.LodgeAccountIngress.objects.filter(
            lodge_account__handler__lodge=self.lodge
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['lodge'] = self.lodge
        return context


class LodgeAccountIngressDetailView(LoginRequiredMixin, DetailView):
    model = models.LodgeAccountIngress
    context_object_name = 'ingress'
    template_name = 'treasure/lodgeaccountingress_detail.html'


class LodgeAccountIngressCreateView(LoginRequiredMixin, CreateView):
    model = models.LodgeAccountIngress
    fields = [
        'lodge_account',
        'ingress_type',
        'amount',
        'description',
        'receipt'
    ]
    template_name = 'treasure/lodgeaccountingress_add.html'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.last_modified_by = self.request.user
        return super().form_valid(form)


class LodgeAccountEgressesByLodgeList(LoginRequiredMixin, ListView):
    template_name = 'treasure/lodgeaccountegresses_list.html'
    context_object_name = 'egresses'

    def get_queryset(self):
        self.lodge = get_object_or_404(
            users.Lodge, pk=self.kwargs['pk']
        )
        return models.LodgeAccountEgress.objects.filter(
            lodge_account__handler__lodge=self.lodge
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['lodge'] = self.lodge
        return context


class LodgeAccountEgressDetailView(LoginRequiredMixin, DetailView):
    model = models.LodgeAccountEgress
    context_object_name = 'egress'
    template_name = 'treasure/lodgeaccountegress_detail.html'


class LodgeAccountEgressCreateView(LoginRequiredMixin, CreateView):
    model = models.LodgeAccountEgress
    fields = [
        'lodge_account',
        'egress_type',
        'amount',
        'description',
        'receipt'
    ]
    template_name = 'treasure/lodgeaccountegress_add.html'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.last_modified_by = self.request.user
        return super().form_valid(form)

hijos/templates/users/affiliation_add.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}{% trans "add affiliation" %}{% endblock %}

{% block content %}
  <h1>{% trans "Affiliation" %}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:affiliation-create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">{% trans "Add" %}</button>
      </div>
    </div>
  </form>
{% endblock %}

hijos/templates/users/affiliation_detail.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}{% trans "affiliation detail" %}{% endblock %}

{% block content %}
<div class="row">
  <div class="col"><h1>{% trans "Affiliation" %} #{{ affiliation.id }}</h1></div>
</div>
<div class="row">
  <div class="col">
    {% trans "Lodge" %}: <a href="{% url 'users:lodge-detail' affiliation.lodge.id %}">{{ affiliation.lodge }}</a>
  </div>
</div>
<div class="row">
  <div class="col">
    {% trans "User" %}: <a href="{% url 'users:user-detail' affiliation.user.username %}">{{ affiliation.user }}</a>
  </div>
</div>
<div class="row">
  <div class="col">
    <b>{% trans "Balance" %} $ {{ affiliation.account.balance }}</b>
  </div>
</div>
<br>
<table class="table table-striped">
  <thead>
    <tr>
      <th>{% trans "Movement" %}</th>
      <th>{% trans "Amount" %}</th>
      <th>{% trans "Balance" %}</th>
      <th>{% trans "Created by" %}</th>
      <th>{% trans "Created on" %}</th>
    </tr>
  </thead>
  <tbody>
    {% for movement in affiliation.account.movements.all %}
    {% if movement.is_active %}
    <tr>
      {% if movement.account_movement_type == "I" %}
      <td>{% trans "Invoice" %}</td>
      {% elif movement.account_movement_type == "D" %}
      <td>{% trans "Deposit" %}</td>
      {% elif movement.account_movement_type == "C" %}
      <td>{% trans "Charge" %}</td>
      {% elif movement.account_movement_type == "G" %}
      <td>{% trans "Grand Lodge Deposit" %}</td>
      {% else %}
      <td>{% trans "Unknown" %}</td>
      {% endif %}
      <td>$ {{ movement.amount }}</td>
      <td>$ {{ movement.balance }}</td>
      <td>{{ movement.created_by }}</td>
      <td>{{ movement.created_on  }}</td>
    </tr>
    {% endif %}
    {% endfor %}
  </tbody>
</table>
<form class="form-horizontal" method="post" action="{% url 'users:affiliation-detail' affiliation.id %}">
  {% csrf_token %}
  <div class="control-group">
  <div class="controls">
    <button type="submit" class="btn">
        {% trans "Send Email with Account Balance" %}
    </button>
  </div>
  </div>
</form>
{% endblock %}

hijos/templates/users/affiliation_list.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}{% trans "affiliation list" %}{% endblock %}

{% block content %}
<div class="row">
  <div class="col"><h1>{% trans "Affiliations" %} - {{ lodge }}</h1></div>
</div>
<div class="row">
  <div class="col">
    <ul>
      {% for affiliation in affiliations %}
      <div class="row">
        <div class="col">
          <a href="{% url 'users:affiliation-detail' affiliation.id %}">
            <b>{{ affiliation }}</b>
          </a>
        </div>
      </div>
      {% endfor %}
    </ul>
  </div>
  <div class="row">
    <div class="col">
      {% trans "Total entries" %} {{ affiliations.count }}
    </div>
  </div>
</div>
{% endblock %}

hijos/templates/users/lodge_detail.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}{% trans "lodge detail" %}{% endblock %}

{% block content %}
<div class="row">
  <div class="col"><h1>{% trans "Lodge" %} {{ lodge }}</h1></div>
</div>
<div class="row">
  <div class="col">
    <ul>
      {% for affiliation in lodge.affiliations.all %}
      {% if affiliation.is_active %}
      <div class="row">
        <div class="col">
          <a href="{% url 'users:affiliation-detail' affiliation.id %}">
            <b>{{ affiliation }}</b>
          </a>
        </div>
      </div>
      {% endif %}
      {% endfor %}
    </ul>
  </div>
</div>
<div class="row">
  <div class="col">
    {% trans "Total entries" %} {{ lodge.affiliations.count }}
  </div>
</div>
<br>
<div class="row">
  <div class="col"><h3>{% trans "Listings filtered by this lodge" %}</h1></div>
</div>
<div class="row">
  <div class="col">
    <li>
      <a href="{% url 'treasure:lodgeaccount-list' lodge.id %}">
        {% trans "List Lodge Accounts" %}
      </a>
    </li>
    <li>
      <a href="{% url 'treasure:debtor-list' lodge.id %}">
        {% trans "List Debtors" %}
      </a>
    </li>
    <li>
      <a href="{% url 'treasure:period-list' lodge.id %}">
        {% trans "List Periods" %}
      </a>
    </li>
    <li>
      <a href="{% url 'treasure:invoice-list' lodge.id %}">
        {% trans "List Invoices" %}
      </a>
    </li>
    <li>
      <a href="{% url 'treasure:charge-list' lodge.id %}">
        {% trans "List Charges" %}
      </a>
    </li>
    <li>
      <a href="{% url 'treasure:deposit-list' lodge.id %}">
        {% trans "List Deposit" %}
      </a>
    </li>
    <li>
      <a href="{% url 'treasure:grandlodgedeposit-list' lodge.id %}">
        {% trans "List Grand Lodge Deposits" %}
      </a>
    </li>
    <li>
      <a href="{% url 'treasure:lodgeaccountingress-list' lodge.id %}">
        {% trans "List Ingresses" %}
      </a>
    </li>
    <li>
      <a href="{% url 'treasure:lodgeaccountegress-list' lodge.id %}">
        {% trans "List Egresses" %}
      </a>
    </li>
    <li>
      <a href="{% url 'treasure:lodgeaccounttransfer-list' lodge.id %}">
        {% trans "List Transfers" %}
      </a>
    </li>
  </div>
</div>
<br>
<div class="row">
  <div class="col"><h3>{% trans "Actions" %}</h1></div>
</div>
<div class="row">
  <form class="form-horizontal" method="post" action="{% url 'users:lodge-detail' lodge.id %}">
    {% csrf_token %}
    <div class="control-group">
    <div class="controls">
      <button type="submit" class="btn">
        {% trans "Send Mass Email with Account Balance" %}
      </button>
    </div>
    </div>
  </form>
</div>
{% endblock %}

hijos/templates/users/lodge_list.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}{% trans "lodge list" %}{% endblock %}

{% block content %}
<div class="row">
  <div class="col"><h1>{% trans "Lodges" %}</h1></div>
</div>
<div class="row">
  <div class="col">
    <ul>
      {% for lodge in lodges %}
      <div class="row">
        <div class="col">
          <a href="{% url 'users:lodge-detail' lodge.id %}">
            <b>{{ lodge }}</b>
          </a>
        </div>
      </div>
      {% endfor %}
    </ul>
  </div>
</div>
{% endblock %}

hijos/templates/users/user_add.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}{% trans "add user" %}{% endblock %}

{% block content %}
  <h1>{% trans "User" %}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:user-create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">{% trans "Add" %}</button>
      </div>
    </div>
  </form>
{% endblock %}

hijos/templates/users/user_detail.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}{% trans "user detail" %}{% endblock %}

{% block content %}
<div class="row">
  <div class="col"><h1>{% trans "User Profile" %}</h1></div>
</div>
<div class="row">
  <div class="col">
    <h3>{{ user }}</h3>
  </div>
</div>
<div class="row">
  <div class="col">
    {% trans "Title" %}: 
    {% if user.most_worshipful %}
      {% trans "Most Worshipful Brother" %}
    {% elif user.worshipful %}
      {% trans "Worshipful Brother" %}
    {% elif user.past_master %}
      {% trans "Worshipful Master" %}
    {% else %}
      {% trans "Brother" %}
    {% endif %}
  </div>
</div>
{% if user.initiated %}
<div class="row">
  <div class="col">{% trans "Initiated on" %} {{ user.initiated }}</div>
</div>
{% endif %}
{% if user.passed %}
<div class="row">
  <div class="col">{% trans "Passed on" %} {{ user.passed }}</div>
</div>
{% endif %}
{% if user.raised %}
<div class="row">
  <div class="col">{% trans "Raised on" %} {{ user.passed }}</div>
</div>
{% endif %}
<div class="row">
  <div class="col"><h2>{% trans "Treasure" %}</h2></div>
</div>
<div class="row">
  <div class="col">
    <ul>
      {% for affiliation in user.affiliations.all %}
        <div class="row">
          <div class="col"><b>{{ affiliation.lodge.name }}</b></div>
        </div>
        <div class="row">
          <div class="col">
            <b>{% trans "Balance" %} $ {{ affiliation.account.balance }}</b>
          </div>
        </div>
        <br>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>{% trans "Movement" %}</th>
              <th>{% trans "Amount" %}</th>
              <th>{% trans "Balance" %}</th>
              <th>{% trans "Created by" %}</th>
              <th>{% trans "Created on" %}</th>
            </tr>
          </thead>
          <tbody>
          {% for movement in affiliation.account.movements.all %}
            {% if movement.is_active %}
            <tr>
              {% if movement.account_movement_type == "I" %}
              <td>{% trans "Invoice" %}</td>
              {% elif movement.account_movement_type == "D" %}
              <td>{% trans "Deposit" %}</td>
              {% elif movement.account_movement_type == "C" %}
              <td>{% trans "Charge" %}</td>
              {% elif movement.account_movement_type == "G" %}
              <td>{% trans "Grand Lodge Deposit" %}</td>
              {% else %}
              <td>{% trans "Unknown" %}</td>
              {% endif %}
              <td>$ {{ movement.amount }}</td>
              <td>$ {{ movement.balance }}</td>
              <td>{{ movement.created_by }}</td>
              <td>{{ movement.created_on  }}</td>
            </tr>
            {% endif %}
          {% endfor %}
          </tbody>
        </table>
      {% endfor %}
    </ul>
  </div>
</div>
{% endblock %}

hijos/templates/users/user_form.html
{% extends "base.html" %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Update</button>
      </div>
    </div>
  </form>
{% endblock %}

hijos/templates/users/user_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Members{% endblock %}

{% block content %}
<div class="container">
  <h2>Users</h2>

  <div class="list-group">
    {% for user in user_list %}
      <a href="{% url 'users:user-detail' user.username %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ user.username }}</h4>
      </a>
    {% endfor %}
  </div>
  <div class="row">
    <div class="col">
      {% trans "Total entries" %} {{ user_list.count }}
    </div>
  </div>
</div>
{% endblock content %}