config/urls.py
from allauth.account import views as allauth
from django.conf import settings
from django.conf.urls import include
from django.urls import path
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from hijos.users.views import LodgesList

urlpatterns = [
    path(
        '',
        view=LodgesList.as_view(),
        name='home'
    ),

    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),

    # User management
    path('users/', include('hijos.users.urls', namespace='users')),
    path('accounts/login/', allauth.login, name='account_login'),
    path('accounts/logout/', allauth.logout, name='account_logout'),
    # redirect signup to login
    path('accounts/signup/', allauth.login, name='account_signup'),
    path(
        'accounts/password/change/',
        allauth.password_change,
        name='account_change_password'
    ),
    path(
        'accounts/password/set/',
        allauth.password_set,
        name='account_set_password'
    ),
    path(
        'accounts/inactive/',
        allauth.account_inactive,
        name='account_inactive'
    ),
    path('email/', allauth.email, name='account_email'),

    path('treasure/', include('hijos.treasure.urls', namespace='treasure')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path('400/', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        path('403/', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        path('404/', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        path('500/', default_views.server_error),
    ]

hijos/treasure/urls.py
from django.urls import path

from hijos.treasure import forms, views

app_name = 'treasure'
urlpatterns = [
    path(
        'lodges/<int:pk>/lodgeaccounts/',
        view=views.LodgeAccountsByLodgeList.as_view(),
        name='lodgeaccount-list'
    ),
    path(
        'lodgeaccounts/add/',
        view=views.LodgeAccountCreateView.as_view(),
        name='lodgeaccount-create'
    ),
    path(
        'lodgeaccounts/<int:pk>/',
        view=views.LodgeAccountDetailView.as_view(),
        name='lodgeaccount-detail'
    ),
    path(
        'lodges/<int:pk>/periods/',
        view=views.PeriodsByLodgeList.as_view(),
        name='period-list'
    ),
    path(
        'periods/add/',
        view=views.PeriodCreateView.as_view(),
        name='period-create'
    ),
    path(
        'periods/<int:pk>/',
        view=views.PeriodDetailView.as_view(),
        name='period-detail'
    ),
    path(
        'lodges/<int:pk>/invoices/',
        view=views.InvoicesByLodgeList.as_view(),
        name='invoice-list'
    ),
    path(
        'invoices/add/',
        view=views.InvoiceCreateView.as_view(),
        name='invoice-create'
    ),
    path(
        'invoices/<int:pk>/',
        view=views.InvoiceDetailView.as_view(),
        name='invoice-detail'
    ),
    path(
        'lodges/<int:pk>/deposits/',
        view=views.DepositsByLodgeList.as_view(),
        name='deposit-list'
    ),
    path(
        'deposits/add/',
        view=views.DepositCreateView.as_view(),
        name='deposit-create'
    ),
    path(
        'deposits/<int:pk>/',
        view=views.DepositDetailView.as_view(),
        name='deposit-detail'
    ),
    path(
        'lodges/<int:pk>/charges/',
        view=views.ChargesByLodgeList.as_view(),
        name='charge-list'
    ),
    path(
        'charges/add/',
        view=views.ChargeCreateView.as_view(),
        name='charge-create'
    ),
    path(
        'charges/<int:pk>/',
        view=views.ChargeDetailView.as_view(),
        name='charge-detail'
    ),
    path(
        'lodges/<int:pk>/grandlodgedeposits/',
        view=views.GrandLodgeDepositsByLodgeList.as_view(),
        name='grandlodgedeposit-list'
    ),
    path(
        'grandlodgedeposits/add/',
        view=views.GrandLodgeDepositCreateView.as_view(),
        name='grandlodgedeposit-create'
    ),
    path(
        'grandlodgedeposits/<int:pk>/edit/',
        view=views.GrandLodgeDepositUpdateView.as_view(),
        name='grandlodgedeposit-update'
    ),
    path(
        'grandlodgedeposits/<int:pk>/accredit/',
        view=forms.GrandLodgeDepositAccredit.as_view(),
        name='grandlodgedeposit-accredit'
    ),
    path(
        'grandlodgedeposits/<int:pk>/reject/',
        view=forms.GrandLodgeDepositReject.as_view(),
        name='grandlodgedeposit-reject'
    ),
    path(
        'grandlodgedeposits/<int:pk>/',
        view=views.GrandLodgeDepositDetailView.as_view(),
        name='grandlodgedeposit-detail'
    ),
    path(
        'lodges/<int:pk>/ingresses/',
        view=views.LodgeAccountIngressesByLodgeList.as_view(),
        name='lodgeaccountingress-list'
    ),
    path(
        'ingresses/add/',
        view=views.LodgeAccountIngressCreateView.as_view(),
        name='lodgeaccountingress-create'
    ),
    path(
        'ingresses/<int:pk>/',
        view=views.LodgeAccountIngressDetailView.as_view(),
        name='lodgeaccountingress-detail'
    ),
    path(
        'lodges/<int:pk>/egresses/',
        view=views.LodgeAccountEgressesByLodgeList.as_view(),
        name='lodgeaccountegress-list'
    ),
    path(
        'egresses/add/',
        view=views.LodgeAccountEgressCreateView.as_view(),
        name='lodgeaccountegress-create'
    ),
    path(
        'egresses/<int:pk>/',
        view=views.LodgeAccountEgressDetailView.as_view(),
        name='lodgeaccountegress-detail'
    ),
    path(
        'lodges/<int:pk>/transfers/',
        view=views.LodgeAccountTransfersByLodgeList.as_view(),
        name='lodgeaccounttransfer-list'
    ),
    path(
        'transfers/add/',
        view=views.LodgeAccountTransferCreateView.as_view(),
        name='lodgeaccounttransfer-create'
    ),
    path(
        'transfers/<int:pk>/',
        view=views.LodgeAccountTransferDetailView.as_view(),
        name='lodgeaccounttransfer-detail'
    ),
    path(
        'lodges/<int:pk>/debtors/',
        view=views.DebtorsByLodgeList.as_view(),
        name='debtor-list'
    )
]

hijos/users/urls.py
from django.urls import path

from hijos.users import views

app_name = 'users'
urlpatterns = [
    path(
        'users/',
        view=views.UserListView.as_view(),
        name='user-list'
    ),
    path(
        'users/add/',
        view=views.UserCreateView.as_view(),
        name='user-create'
    ),
    path(
        'users/<username>/',
        view=views.UserDetailView.as_view(),
        name='user-detail'
    ),
    path(
        'lodges/',
        view=views.LodgesList.as_view(),
        name='lodge-list'
    ),
    path(
        'lodges/<int:pk>/',
        view=views.LodgeDetailView.as_view(),
        name='lodge-detail'
    ),
    path(
        'lodges/<int:pk>/affiliations/',
        view=views.AffiliationsByLodgeList.as_view(),
        name='affiliation-list'
    ),
    path(
        'affiliations/<int:pk>/',
        view=views.AffiliationDetailView.as_view(),
        name='affiliation-detail'
    ),
    path(
        'affiliations/add/',
        view=views.AffiliationCreateView.as_view(),
        name='affiliation-create'
    )
]

hijos/treasure/views.py
from decimal import Decimal

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Avg, Max, Min, Q, Sum
from django.shortcuts import get_object_or_404
from django.views.generic import CreateView, DetailView, ListView, UpdateView

from hijos.treasure import models
from hijos.users import models as users


class LodgeAccountsByLodgeList(LoginRequiredMixin, ListView):
    template_name = 'treasure/lodgeaccount_list.html'
    context_object_name = 'lodge_accounts'

    def get_queryset(self):
        self.lodge = get_object_or_404(
            users.Lodge, pk=self.kwargs['pk']
        )
        return models.LodgeAccount.objects.filter(
            handler__lodge=self.lodge
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['lodge'] = self.lodge
        return context


class LodgeAccountDetailView(LoginRequiredMixin, DetailView):
    model = models.LodgeAccount
    context_object_name = 'lodge_account'
    template_name = 'treasure/lodgeaccount_detail.html'


class LodgeAccountCreateView(LoginRequiredMixin, CreateView):
    model = models.LodgeAccount
    fields = ['handler', 'description']
    template_name = 'treasure/lodgeaccount_add.html'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.last_modified_by = self.request.user
        return super().form_valid(form)


class PeriodsByLodgeList(LoginRequiredMixin, ListView):
    template_name = 'treasure/period_list.html'
    context_object_name = 'periods'

    def get_queryset(self):
        self.lodge = get_object_or_404(
            users.Lodge, pk=self.kwargs['pk']
        )
        return models.Period.objects.filter(
            lodge=self.lodge
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['lodge'] = self.lodge
        return context


class PeriodDetailView(LoginRequiredMixin, DetailView):
    model = models.Period
    context_object_name = 'period'
    template_name = 'treasure/period_detail.html'


class PeriodCreateView(LoginRequiredMixin, CreateView):
    model = models.Period
    fields = ['lodge', 'begin', 'end', 'price_multiplier', 'send_email']
    template_name = 'treasure/period_add.html'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.last_modified_by = self.request.user
        return super().form_valid(form)


class InvoicesByLodgeList(LoginRequiredMixin, ListView):
    template_name = 'treasure/invoice_list.html'
    context_object_name = 'invoices'

    def get_queryset(self):
        self.lodge = get_object_or_404(
            users.Lodge, pk=self.kwargs['pk']
        )
        return models.Invoice.objects.filter(
            period__lodge=self.lodge
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['lodge'] = self.lodge
        return context


class InvoiceDetailView(LoginRequiredMixin, DetailView):
    model = models.Invoice
    context_object_name = 'invoice'
    template_name = 'treasure/invoice_detail.html'


class InvoiceCreateView(LoginRequiredMixin, CreateView):
    model = models.Invoice
    fields = ['period', 'affiliation', 'amount', 'send_email']
    template_name = 'treasure/invoice_add.html'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.last_modified_by = self.request.user
        return super().form_valid(form)


class DepositsByLodgeList(LoginRequiredMixin, ListView):
    template_name = 'treasure/deposit_list.html'
    context_object_name = 'deposits'

    def get_queryset(self):
        self.lodge = get_object_or_404(
            users.Lodge, pk=self.kwargs['pk']
        )
        return models.Deposit.objects.filter(
            payer__lodge=self.lodge
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['lodge'] = self.lodge
        return context


class DepositDetailView(LoginRequiredMixin, DetailView):
    model = models.Deposit
    context_object_name = 'deposit'
    template_name = 'treasure/deposit_detail.html'


class DepositCreateView(LoginRequiredMixin, CreateView):
    model = models.Deposit
    fields = [
        'payer',
        'lodge_account',
        'amount',
        'description',
        'send_email',
        'receipt'
    ]
    template_name = 'treasure/deposit_add.html'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.last_modified_by = self.request.user
        return super().form_valid(form)


class ChargesByLodgeList(LoginRequiredMixin, ListView):
    template_name = 'treasure/charge_list.html'
    context_object_name = 'charges'

    def get_queryset(self):
        self.lodge = get_object_or_404(
            users.Lodge, pk=self.kwargs['pk']
        )
        return models.Charge.objects.filter(
            debtor__lodge=self.lodge
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['lodge'] = self.lodge
        return context


class ChargeDetailView(LoginRequiredMixin, DetailView):
    model = models.Charge
    context_object_name = 'charge'
    template_name = 'treasure/charge_detail.html'


class ChargeCreateView(LoginRequiredMixin, CreateView):
    model = models.Charge
    fields = [
        'debtor',
        'charge_type',
        'amount',
        'description',
        'send_email'
    ]
    template_name = 'treasure/charge_add.html'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.last_modified_by = self.request.user
        return super().form_valid(form)


class GrandLodgeDepositsByLodgeList(LoginRequiredMixin, ListView):
    template_name = 'treasure/grandlodgedeposit_list.html'
    context_object_name = 'grand_lodge_deposits'

    def get_queryset(self):
        self.lodge = get_object_or_404(
            users.Lodge, pk=self.kwargs['pk']
        )
        return models.GrandLodgeDeposit.objects.filter(
            payer__lodge=self.lodge
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['lodge'] = self.lodge
        return context


class GrandLodgeDepositDetailView(LoginRequiredMixin, DetailView):
    model = models.GrandLodgeDeposit
    context_object_name = 'grand_lodge_deposit'
    template_name = 'treasure/grandlodgedeposit_detail.html'


class GrandLodgeDepositCreateView(LoginRequiredMixin, CreateView):
    model = models.GrandLodgeDeposit
    fields = [
        'payer',
        'amount',
        'description',
        'receipt',
        'send_email'
    ]
    template_name = 'treasure/grandlodgedeposit_add.html'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.last_modified_by = self.request.user
        return super().form_valid(form)


class GrandLodgeDepositUpdateView(LoginRequiredMixin, UpdateView):
    model = models.GrandLodgeDeposit
    fields = ['receipt']
    template_name = 'treasure/grandlodgedeposit_edit.html'

    def form_valid(self, form):
        form.instance.last_modified_by = self.request.user
        return super().form_valid(form)


class LodgeAccountIngressesByLodgeList(LoginRequiredMixin, ListView):
    template_name = 'treasure/lodgeaccountingresses_list.html'
    context_object_name = 'ingresses'

    def get_queryset(self):
        self.lodge = get_object_or_404(
            users.Lodge, pk=self.kwargs['pk']
        )
        return models.LodgeAccountIngress.objects.filter(
            lodge_account__handler__lodge=self.lodge
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['lodge'] = self.lodge
        return context


class LodgeAccountIngressDetailView(LoginRequiredMixin, DetailView):
    model = models.LodgeAccountIngress
    context_object_name = 'ingress'
    template_name = 'treasure/lodgeaccountingress_detail.html'


class LodgeAccountIngressCreateView(LoginRequiredMixin, CreateView):
    model = models.LodgeAccountIngress
    fields = [
        'lodge_account',
        'ingress_type',
        'amount',
        'description',
        'receipt'
    ]
    template_name = 'treasure/lodgeaccountingress_add.html'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.last_modified_by = self.request.user
        return super().form_valid(form)


class LodgeAccountEgressesByLodgeList(LoginRequiredMixin, ListView):
    template_name = 'treasure/lodgeaccountegresses_list.html'
    context_object_name = 'egresses'

    def get_queryset(self):
        self.lodge = get_object_or_404(
            users.Lodge, pk=self.kwargs['pk']
        )
        return models.LodgeAccountEgress.objects.filter(
            lodge_account__handler__lodge=self.lodge
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['lodge'] = self.lodge
        return context


class LodgeAccountEgressDetailView(LoginRequiredMixin, DetailView):
    model = models.LodgeAccountEgress
    context_object_name = 'egress'
    template_name = 'treasure/lodgeaccountegress_detail.html'


class LodgeAccountEgressCreateView(LoginRequiredMixin, CreateView):
    model = models.LodgeAccountEgress
    fields = [
        'lodge_account',
        'egress_type',
        'amount',
        'description',
        'receipt'
    ]
    template_name = 'treasure/lodgeaccountegress_add.html'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        form.instance.last_modified_by = self.request.user
        return super().form_valid(form)

hijos/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

hijos/templates/base.html
{% load static l10n i18n %}<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">

    <title>hijos - {% block title %}{% endblock %}</title>

    {% block css %}
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    {% endblock %}
  </head>

  <body>
    {% block navbar %}
    {% if request.user.is_authenticated %}
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <a class="navbar-brand" href="#">hijos</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsDefault" aria-controls="navbarsDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsDefault">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'users:lodge-list' %}">{% trans "Lodges" %}</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="/" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% trans "Users" %}</a>
            <div class="dropdown-menu" aria-labelledby="dropdown01">
              <a class="dropdown-item" href="{% url 'users:lodge-list' %}">{% trans "List Lodges" %}</a>
              <a class="dropdown-item" href="{% url 'users:user-list' %}">{% trans "List Users" %}</a>
              <a class="dropdown-item" href="{% url 'users:user-create' %}">{% trans "Add User" %}</a>
              <a class="dropdown-item" href="{% url 'users:affiliation-create' %}">{% trans "Add Affiliation" %}</a>
            </div>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="/" id="dropdown02" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{% trans "Treasure" %}</a>
            <div class="dropdown-menu" aria-labelledby="dropdown02">
              <a class="dropdown-item" href="{% url 'treasure:lodgeaccount-create' %}">{% trans "Add Lodge Account" %}</a>
              <a class="dropdown-item" href="{% url 'treasure:period-create' %}">{% trans "Add Period" %}</a>
              <a class="dropdown-item" href="{% url 'treasure:invoice-create' %}">{% trans "Add Invoice" %}</a>
              <a class="dropdown-item" href="{% url 'treasure:deposit-create' %}">{% trans "Add Deposit" %}</a>
              <a class="dropdown-item" href="{% url 'treasure:charge-create' %}">{% trans "Add Charge" %}</a>
              <a class="dropdown-item" href="{% url 'treasure:grandlodgedeposit-create' %}">{% trans "Add Grand Lodge Deposit" %}</a>
              <a class="dropdown-item" href="{% url 'treasure:lodgeaccountingress-create' %}">{% trans "Add Ingress" %}</a>
              <a class="dropdown-item" href="{% url 'treasure:lodgeaccountegress-create' %}">{% trans "Add Egress" %}</a>
              <a class="dropdown-item" href="{% url 'treasure:lodgeaccounttransfer-create' %}">{% trans "Add Transfers" %}</a>
            </div>
          </li>
        </ul>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:user-detail' request.user.username  %}">{% trans "My Profile" %}</a>
        </li>
        <li class="nav-item">
          {# URL provided by django-allauth/account/urls.py #}
          <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
        </li>
      </div>
    </nav>
    {% endif %}
    {% endblock %}

    <main role="main" class="container">
      {% block content %}
      {% endblock %} 
    </main><!-- /.container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  </body>
</html>